# # PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres_development
  username: postgres
  password: definite
  host: localhost
  port: 5432

test:
  <<: *default
  database: friend_ships_test
  host: localhost
  port: 5432
  username: postgres
  password: definite

production:
  <<: *default
  database: postgres_production
  username: postgres
  password: <%= ENV['POSTGRES_DATABASE_PASSWORD'] %>
  