# # PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ror_social_scaffold_development
  username: ror_social_scaffold
  password: mrSiby3099
  host: localhost
  port: 5432

test:
  <<: *default
  database: friend_ships_test
  host: localhost
  port: 5432
  username: ror_social_scaffold
  password: mrSiby3099

production:
  <<: *default
  database: ror_social_scaffold_production
  username: ror_social_scaffold
  password: <%= ENV['ROR_SOCIAL_SCAFFOLD_DATABASE_PASSWORD'] %>

